plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'dev.mlml.Ilmarinen'
        )
    }
}

compileJava { options.encoding = "UTF-8" }
compileTestJava { options.encoding = "UTF-8" }

var jacksonVersion = '2.13.4'
var lombokVersion = '1.18.38'
var logbackVersion = '1.5.6'
var jdaVersion = '5.6.1'


repositories {
    mavenCentral()
}

dependencies {
    implementation "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"
    implementation "com.fasterxml.jackson.core:jackson-core:$jacksonVersion"
    implementation "com.fasterxml.jackson.core:jackson-annotations:$jacksonVersion"

    compileOnly "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"

    implementation "ch.qos.logback:logback-classic:$logbackVersion"
    implementation("net.dv8tion:JDA:$jdaVersion") {
        exclude module: 'opus-java'
    }
}

shadowJar {
    archiveClassifier.set('')
    manifest {
        attributes['Main-Class'] = 'dev.mlml.Ilmarinen'
    }
}